/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  api: {
    Api: () => import('#controllers/api/api_controller'),
    Auth: () => import('#controllers/api/auth_controller'),
  },
  Profile: () => import('#controllers/profile_controller'),
}
