/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type TransactionTransformer from '#transformers/transaction_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Transaction = InferData<TransactionTransformer>
  export namespace Transaction {
    export type Variants = InferVariants<TransactionTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
